import React, { useState } from 'react';
import { ArrowRight, BarChart3, BrainCircuit, Check, ChevronDown, Database, Download, ExternalLink, Github, Linkedin, Mail, MapPin, Menu, Sparkles, X, Zap } from 'lucide-react';

const projects = [
  { title: "Diagnostic territorial de la protection de l'enfance", category: 'Data Analyse', year: '2026', featured: true, summary: "Analyse de 103 territoires et 18 régions pour comprendre les disparités et l’évolution des mesures ASE entre 2015 et 2024.", metrics: ['103 territoires', '99 territoires en hausse', '2 profils K-means'], tags: ['Python', 'Pandas', 'GeoPandas', 'Scikit-learn'], link: 'https://github.com/Boubanda/diagnostic-territorial-protection-enfance', images: ['/projects/ase/carte-regionale.png', '/projects/ase/evolution-territoires.png', '/projects/ase/profils-territoriaux.png'] },
  { title: 'Analyse de sentiment bancaire', category: 'Intelligence Artificielle', year: '2025', summary: "Solution NLP end-to-end pour classer automatiquement les avis clients et piloter la satisfaction en temps réel.", metrics: ['3 700+ avis', '85% de précision'], tags: ['NLP', 'Random Forest', 'Streamlit'], link: 'https://github.com/Boubanda' },
  { title: 'FraudGuard AI', category: 'Intelligence Artificielle', year: '2025', summary: "Plateforme de détection de fraude bancaire en temps réel, explicable et pensée pour les contraintes métier.", metrics: ['93,5% de précision', 'API < 100 ms'], tags: ['Machine Learning', 'FastAPI', 'XAI'], link: 'https://github.com/Boubanda' },
  { title: 'Extraction OCR — SDNC/DGFiP', category: 'Data Engineering', year: '2025', summary: "Application d’extraction de données administratives avec validation humaine et exports interopérables.", metrics: ['6 champs extraits', 'Fichiers jusqu’à 200 Mo'], tags: ['OCR', 'Tesseract', 'Streamlit'], link: 'https://github.com/Boubanda' },
  { title: 'Dashboard parcours patients', category: 'Data Analyse', year: '2025', summary: "Dashboard R Shiny pour analyser les parcours de soins, les réseaux de professionnels et la téléconsultation.", metrics: ['2 500 patients', '12 000 consultations'], tags: ['R', 'Shiny', 'Plotly'], link: 'https://github.com/Boubanda' },
  { title: 'IA Matching Recrutement', category: 'Intelligence Artificielle', year: '2025', summary: "Moteur de matching entre candidatures et offres combinant extraction NLP et scoring XGBoost.", metrics: ['87% matching', '-60% temps de tri'], tags: ['NLP', 'XGBoost', 'Mistral'], link: 'https://github.com/Boubanda' },
  { title: 'Prédiction de la qualité du vin', category: 'Data Science', year: '2025', summary: "Comparaison rigoureuse de modèles de régression pour prédire la qualité de 6 497 vins.", metrics: ['6 497 échantillons', 'R² = 0,60'], tags: ['Random Forest', 'SVR', 'Scikit-learn'], link: 'https://github.com/Boubanda' },
  { title: 'Données de montres connectées', category: 'Data Engineering', year: '2024', summary: "Pipeline sécurisé de collecte et de traitement de données issues de Google Fit et Fitbit.", metrics: ['15 000+ mesures', 'OAuth 2.0'], tags: ['API', 'Pandas', 'NumPy'], link: 'https://github.com/Boubanda' },
  { title: 'Automatisation Data — Fairmat', category: 'Data Engineering', year: '2024', summary: "Pipeline ETL et catégorisation automatique pour identifier des opportunités dans l’économie circulaire.", metrics: ['14 631 lignes', '96% de précision'], tags: ['Selenium', 'ETL', 'Power BI'], link: 'https://github.com/Boubanda' }
];

const skills = [
  [BarChart3, 'Data Analyse', 'Analyse exploratoire, statistiques, KPI et visualisation', 'Pandas · Power BI · Tableau · Plotly'],
  [BrainCircuit, 'IA & Machine Learning', 'Modélisation, évaluation, NLP et Deep Learning', 'Scikit-learn · PyTorch · TensorFlow'],
  [Database, 'Data Engineering', 'Collecte, qualité, ETL et bases de données', 'SQL · MongoDB · Airflow · Spark'],
  [Zap, 'Déploiement', 'APIs, conteneurisation et industrialisation', 'FastAPI · Docker · Azure · CI/CD']
];

const filters = ['Tous', 'Data Analyse', 'Data Science', 'Intelligence Artificielle', 'Data Engineering'];

export default function App() {
  const [filter, setFilter] = useState('Tous');
  const [all, setAll] = useState(false);
  const [menu, setMenu] = useState(false);
  const filtered = projects.filter(p => filter === 'Tous' || p.category === filter);
  const visible = all || filter !== 'Tous' ? filtered : filtered.slice(0, 6);
  const go = id => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' }); setMenu(false); };

  return <main className="min-h-screen overflow-x-hidden bg-[#07111f] text-slate-100 selection:bg-cyan-300 selection:text-slate-950">
    <nav className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#07111f]/85 backdrop-blur-xl">
      <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
        <button onClick={() => go('accueil')} className="flex items-center gap-3 text-left"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cyan-300 font-black text-slate-950">LB</span><span><strong className="block text-sm">Levi Boubanda</strong><small className="text-xs text-slate-400">Data & IA</small></span></button>
        <div className="hidden items-center gap-8 md:flex">{['projets', 'expertise', 'parcours', 'contact'].map(x => <button key={x} onClick={() => go(x)} className="text-sm capitalize text-slate-300 hover:text-cyan-300">{x}</button>)}</div>
        <a href="mailto:leviboubanda07@gmail.com" className="hidden rounded-full bg-cyan-300 px-5 py-2.5 text-sm font-bold text-slate-950 hover:bg-cyan-200 md:inline-flex">Me contacter</a>
        <button aria-label="Menu" onClick={() => setMenu(!menu)} className="rounded-lg border border-white/10 p-2 md:hidden">{menu ? <X /> : <Menu />}</button>
      </div>
      {menu && <div className="border-t border-white/10 px-5 py-4 md:hidden">{['projets', 'expertise', 'parcours', 'contact'].map(x => <button key={x} onClick={() => go(x)} className="block w-full py-3 text-left capitalize">{x}</button>)}</div>}
    </nav>

    <section id="accueil" className="relative mx-auto grid min-h-screen max-w-7xl items-center gap-14 px-5 pb-20 pt-32 lg:grid-cols-[1.15fr_.85fr] lg:px-8">
      <div className="absolute left-1/2 top-20 h-96 w-96 rounded-full bg-cyan-400/10 blur-[120px]" />
      <div className="relative"><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-4 py-2 text-sm text-emerald-200"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-300" /> Alternance dès septembre 2026</div><p className="mb-5 font-mono text-sm uppercase tracking-[.24em] text-cyan-300">Data Analyst · Data Scientist · IA</p><h1 className="max-w-4xl text-5xl font-black leading-[1.03] tracking-tight sm:text-6xl lg:text-7xl">Je transforme les données en <span className="text-gradient">décisions utiles.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">Étudiant en Bac+4 à Aivancity, je conçois des analyses, modèles et produits data de bout en bout avec une attention particulière portée à l’impact métier et social.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => go('projets')} className="inline-flex items-center gap-2 rounded-full bg-cyan-300 px-6 py-3.5 font-bold text-slate-950 hover:bg-cyan-200">Voir mes projets <ArrowRight size={18} /></button><a href="/CV_Levi_data_analyst.pdf" download className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3.5 font-semibold hover:bg-white/5"><Download size={18} /> Télécharger mon CV</a></div><div className="mt-12 grid max-w-2xl grid-cols-3 gap-3">{[['9', 'projets'], ['4', 'domaines data'], ['2027', 'diplôme Bac+5']].map(([n, l]) => <div key={l} className="border-l border-white/15 pl-4"><strong className="block text-2xl">{n}</strong><span className="text-xs text-slate-400 sm:text-sm">{l}</span></div>)}</div></div>
      <div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-5 rotate-3 rounded-[2.5rem] border border-cyan-300/20 bg-cyan-300/5" /><div className="relative overflow-hidden rounded-[2.5rem] border border-white/10 bg-slate-900 shadow-2xl"><img src="/photo.jpeg" alt="Levi Junior Boubanda" className="aspect-[4/5] w-full object-cover object-top" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950 via-slate-950/80 to-transparent p-7 pt-24"><p className="font-bold">Levi Junior BOUBANDA</p><p className="mt-1 text-sm text-slate-300">Aivancity · Programme Grande École IA & Data</p><div className="mt-4 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-1 text-xs">Paris</span><span className="rounded-full bg-white/10 px-3 py-1 text-xs">3 sem. entreprise / 1 sem. école</span></div></div></div></div>
    </section>

    <section id="projets" className="border-y border-white/10 bg-white/[.025] py-24"><div className="mx-auto max-w-7xl px-5 lg:px-8"><Title eyebrow="Portfolio" title="Des projets concrets, de la donnée à l’impact." text="Une sélection de cas end-to-end : cadrage, préparation, analyse, modélisation et restitution." /><Featured /><div className="mt-14 flex gap-2 overflow-x-auto pb-3">{filters.map(x => <button key={x} onClick={() => { setFilter(x); setAll(true); }} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm ${filter === x ? 'bg-cyan-300 font-bold text-slate-950' : 'border border-white/10 text-slate-300'}`}>{x}</button>)}</div><div className="mt-6 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{visible.filter(p => !p.featured).map(p => <Card key={p.title} p={p} />)}</div>{filter === 'Tous' && !all && <div className="mt-9 text-center"><button onClick={() => setAll(true)} className="inline-flex items-center gap-2 rounded-full border border-white/15 px-5 py-3 font-semibold hover:bg-white/5">Voir tous les projets <ChevronDown size={18} /></button></div>}</div></section>

    <section id="expertise" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><Title eyebrow="Expertise" title="Une vision complète de la chaîne data." text="J’associe rigueur analytique, compréhension métier et capacité à rendre les résultats accessibles." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{skills.map(([Icon, title, text, tools]) => <article key={title} className="group rounded-3xl border border-white/10 bg-white/[.035] p-6 transition hover:-translate-y-1 hover:border-cyan-300/30"><div className="mb-8 grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/10 text-cyan-300 group-hover:bg-cyan-300 group-hover:text-slate-950"><Icon /></div><h3 className="text-xl font-bold">{title}</h3><p className="mt-3 min-h-16 text-sm leading-6 text-slate-400">{text}</p><p className="mt-6 border-t border-white/10 pt-5 text-xs leading-5 text-cyan-200">{tools}</p></article>)}</div></section>

    <section id="parcours" className="border-y border-white/10 bg-[#0a1728] py-24"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-2 lg:px-8"><div><Title eyebrow="À propos" title="Curieux, rigoureux et orienté solution." text="Je souhaite rejoindre une équipe où la donnée répond à des enjeux réels et progresser au contact de profils expérimentés." /><div className="flex flex-wrap gap-2">{['Esprit analytique', 'Autonomie', 'Communication', 'Curiosité', 'Travail en équipe'].map(x => <span key={x} className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-sm text-slate-300">{x}</span>)}</div></div><div className="space-y-4"><Timeline year="2023 — 2027" title="Programme Grande École IA & Data" place="Aivancity School of Technology · Bac+5" current /><Timeline year="2020 — 2022" title="Classe préparatoire Mathématiques & Physique" place="École Supérieure Privée d’Ingénieur" /><Timeline year="2020" title="Baccalauréat technologique" place="Lycée technique Omar Bongo" /></div></div></section>

    <section id="contact" className="mx-auto max-w-5xl px-5 py-24 text-center"><div className="rounded-[2rem] border border-cyan-300/20 bg-gradient-to-br from-cyan-300/10 via-transparent to-blue-500/10 px-6 py-16 sm:px-12"><Sparkles className="mx-auto mb-5 text-cyan-300" /><p className="font-mono text-xs uppercase tracking-[.24em] text-cyan-300">Construisons quelque chose d’utile</p><h2 className="mx-auto mt-5 max-w-3xl text-4xl font-black sm:text-5xl">Vous recherchez un profil Data & IA motivé ?</h2><p className="mx-auto mt-5 max-w-2xl text-slate-300">Disponible pour une alternance d’un an dès septembre 2026, au rythme de trois semaines en entreprise et une semaine à l’école.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><a href="mailto:leviboubanda07@gmail.com" className="inline-flex items-center gap-2 rounded-full bg-cyan-300 px-6 py-3.5 font-bold text-slate-950"><Mail size={18} /> Échangeons</a><a href="https://www.linkedin.com/in/l%C3%A9vi-junior016/" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full border border-white/15 px-6 py-3.5 font-semibold"><Linkedin size={18} /> LinkedIn</a></div></div></section>

    <footer className="border-t border-white/10 px-5 py-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 text-sm text-slate-500 sm:flex-row"><p>© 2026 Levi Junior BOUBANDA</p><div className="flex items-center gap-5"><span className="inline-flex items-center gap-1"><MapPin size={14} /> Île-de-France</span><a href="https://github.com/Boubanda" target="_blank" rel="noreferrer"><Github size={19} /></a><a href="https://www.linkedin.com/in/l%C3%A9vi-junior016/" target="_blank" rel="noreferrer"><Linkedin size={19} /></a></div></div></footer>
  </main>;
}

function Title({ eyebrow, title, text }) { return <div className="mb-12 max-w-3xl"><p className="font-mono text-xs uppercase tracking-[.24em] text-cyan-300">{eyebrow}</p><h2 className="mt-4 text-3xl font-black tracking-tight sm:text-5xl">{title}</h2><p className="mt-5 text-base leading-7 text-slate-400 sm:text-lg">{text}</p></div>; }

function Featured() { const p = projects[0]; return <article className="overflow-hidden rounded-[2rem] border border-cyan-300/20 bg-[#0b1a2c]"><div className="grid lg:grid-cols-[.9fr_1.1fr]"><div className="p-7 sm:p-10"><div className="inline-flex items-center gap-2 rounded-full bg-cyan-300/10 px-3 py-1.5 text-xs font-semibold text-cyan-200"><Sparkles size={14} /> Projet à la une</div><h3 className="mt-6 text-3xl font-black">{p.title}</h3><p className="mt-5 leading-7 text-slate-300">{p.summary}</p><div className="mt-7 grid gap-2 sm:grid-cols-3">{p.metrics.map(x => <div key={x} className="rounded-xl border border-white/10 bg-white/5 p-3 text-sm font-semibold"><Check className="mb-2 text-emerald-300" size={16} />{x}</div>)}</div><div className="mt-6 flex flex-wrap gap-2">{p.tags.map(x => <span key={x} className="rounded-full bg-white/5 px-3 py-1 text-xs text-slate-300">{x}</span>)}</div><a href={p.link} target="_blank" rel="noreferrer" className="mt-8 inline-flex items-center gap-2 font-bold text-cyan-300">Explorer le projet <ExternalLink size={17} /></a></div><div className="grid min-h-96 grid-cols-2 gap-px bg-white/10">{p.images.map((src, i) => <a key={src} href={src} target="_blank" rel="noreferrer" className={`${i === 0 ? 'col-span-2' : ''} overflow-hidden bg-white`}><img src={src} alt="Visualisation du projet ASE" className="h-full w-full object-contain transition duration-500 hover:scale-[1.025]" /></a>)}</div></div></article>; }

function Card({ p }) { return <article className="group flex min-h-80 flex-col rounded-3xl border border-white/10 bg-[#0a1728] p-6 transition hover:-translate-y-1 hover:border-cyan-300/25"><div className="flex items-center justify-between text-xs"><span className="rounded-full bg-white/5 px-3 py-1.5 text-cyan-200">{p.category}</span><span className="text-slate-500">{p.year}</span></div><h3 className="mt-6 text-xl font-bold group-hover:text-cyan-200">{p.title}</h3><p className="mt-3 flex-1 text-sm leading-6 text-slate-400">{p.summary}</p><div className="mt-5 flex flex-wrap gap-2">{p.metrics.map(x => <span key={x} className="text-xs font-semibold">• {x}</span>)}</div><div className="mt-6 flex items-end justify-between border-t border-white/10 pt-5"><div className="flex flex-wrap gap-1">{p.tags.map(x => <span key={x} className="rounded bg-white/5 px-2 py-1 text-[11px] text-slate-400">{x}</span>)}</div><a aria-label={`Voir ${p.title}`} href={p.link} target="_blank" rel="noreferrer" className="rounded-full border border-white/10 p-2 hover:text-cyan-300"><ArrowRight size={17} /></a></div></article>; }

function Timeline({ year, title, place, current }) { return <div className="relative rounded-2xl border border-white/10 bg-white/[.035] p-6 pl-8"><span className={`absolute left-0 top-8 h-12 w-1 rounded-r ${current ? 'bg-cyan-300' : 'bg-slate-600'}`} /><p className="font-mono text-xs text-cyan-300">{year}</p><h3 className="mt-3 text-lg font-bold">{title}</h3><p className="mt-1 text-sm text-slate-400">{place}</p>{current && <span className="absolute right-5 top-5 rounded-full bg-emerald-300/10 px-3 py-1 text-xs text-emerald-200">En cours</span>}</div>; }
